homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret lat
  longitude: !secret lon
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 3
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: !secret timezone
  # Customization file
  customize: !include customize.yaml
  customize_glob: !include customize_glob.yaml

# Show links to resources in log and frontend
#introduction:

zone:
  name: Home
  latitude: !secret lat
  longitude: !secret lon
  radius: 150
  icon: mdi:account-multiple

# Enables the frontend
frontend: !include frontend.yaml

# Enables configuration UI
config:

http:
  base_url: !secret base_url
  # Secrets are defined in the file secrets.yaml
  api_password: !secret http_password
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  # base_url: example.duckdns.org:8123

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

# Weather prediction
# sensor:
#   - platform: yr

# ffmpeg:
#   ffmpeg_bin: /usr/bin/ffmpeg

xiaomi_aqara:
  gateways:
    - mac:
      key: !secret xiaomi_aqara_key

ifttt:
  key: !secret ifttt_key

# google_assistant:
#   project_id: home-assistant-183914
#   client_id: 324880814170-tprj6emm17h0k2779sl214a4rt1fd475.apps.googleusercontent.com
#   access_token: !secret google_assistant_token
#   exposed_domains:
#     - switch
#     - light
#     - group

# Text to speech
tts:
  - platform: google

zoneminder:
  host: !secret zoneminder_host

# Singles
#scene: !include scenes.yaml
automation: !include automations.yaml
script: !include scripts.yaml
camera: !include devices/cameras.yaml
weblink: !include weblinks.yaml
media_player: !include media_players.yaml
device_tracker: !include devices/device_trackers.yaml
sensor: !include devices/sensors.yaml
switch: !include devices/switches.yaml
light: !include devices/lights.yaml
notify: !include notify.yaml
#customizer: !include config/customizer.yaml

# Merge named
group: !include_dir_merge_named groups


